### ISSUE TITLE
Extract sync-defaults action

### ISSUE THREAD

**Issue by patcon** [exivity/actions#265]
Hi there! I came across your repo via https://github.com/probot/settings/issues/518#issuecomment-1054428235

I feel like your solution here is really great, but it seems that I can't actually use this GitHub Action outside the context of exivity. Is that correct?

These are my failed attempts, for what it's worth:
https://github.com/g0v-network/domains/actions/workflows/sync-repo-settings.yml

Curious to know your thoughts! Wondering if maybe (so as not to get in the way of your monorepo flow) the org owner could just be made more configurable here, as I believe that's part of the snag :)

https://github.com/exivity/actions/blob/cf6cca87f5779184649084cdf63e1fafa5e0e914/sync-defaults/src/settings/index.ts#L36-L39

---

PS, you might get a kick out of using this github action to get ephemeral tokens from a github app scoped to just your organization: https://github.com/peter-murray/workflow-application-token-action

**Comment by hongaar** [comment]
Hi! Thanks for chiming in here. Your feedback is appreciated and you make a valid point. Currently, this repo is not ready for use outside the exivity org.

I'll make an attempt to make the actions in this repo more generic to make them more re-usable (e.g. infer the owner from the current repo owner by default, etc.).

> PS, you might get a kick out of using this github action to get ephemeral tokens from a github app scoped to just your organization: https://github.com/peter-murray/workflow-application-token-action

Interesting approach, I'll try this!

**Comment by hongaar** [comment]
@patcon I've prepared a branch which should be usable outside of the exivity org. If you have a chance, could you try these changes by using like this and let me know the results?
```yaml
uses: exivity/actions/sync-defaults@feat/generalize
```

**Comment by hongaar** [comment]
@patcon I've prepared a branch which should be usable outside of the exivity org. If you have a chance, could you try these changes by using like this and let me know the results?
```yaml
uses: exivity/actions/sync-defaults@feat/generalize
```
